version: '3'

services:
  php:
    build:
      context: docker/php
    volumes:
      - ./:/var/www/app
    user: "1000:1000"
    environment:
      DATABASE_URL: mysql://root:root@database/db
      APP_SECRET: APP_SECRET
  nginx:
    build: docker/nginx
    ports:
      - 8086:80
    volumes_from:
      - php
    volumes:
      - ./docker/nginx/logs:/var/log/nginx
  database:
    image: mysql:5.7.30
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_DATABASE: db
    volumes:
        - ./docker/mysql:/var/lib/mysql
  rabbit1:
    image: rabbitmq:3-management
    environment:
      RABBITMQ_ERLANG_COOKIE: "SWQOKODSQALRPCLNMEQG"
      RABBITMQ_DEFAULT_USER: "rabbitmq"
      RABBITMQ_DEFAULT_PASS: "rabbitmq"
      RABBITMQ_DEFAULT_VHOST: "/"
    ports:
      - 15673:15672
      - 5673:5672
    labels:
      NAME: "rabbitmq1" 
  worker:
    build:
      context: docker/worker
    volumes:
      - ./:/var/www/app
    environment:
      MESSENGER_TRANSPORT_DSN: amqp://rabbitmq:rabbitmq@rabbit1:5672/%2f/messages
    restart: always
    user: "1000:1000"
